# Generated by Django 4.2.23 on 2025-08-11 16:28

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer's full name (2-100 characters)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Customer's primary email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone number (minimum 10 characters)",
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current account balance (0.00 to 99,999,999.99)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(99999999.99),
                        ],
                    ),
                ),
                (
                    "credit_score",
                    models.IntegerField(
                        help_text="Credit score (300-850 range)",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(850),
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.FloatField(
                        help_text="Interest rate percentage (0.0-30.0%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(30.0),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the customer account is active"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when customer account was created",
                    ),
                ),
                (
                    "last_contact_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time of last customer contact (optional)",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
