# Generated by Django 4.2.23 on 2025-08-11 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order identifier', max_length=20, unique=True)),
                ('customer_name', models.CharField(help_text="Customer's full name (required)", max_length=100)),
                ('customer_email', models.EmailField(help_text="Customer's email address (required)", max_length=254)),
                ('shipping_address', models.TextField(help_text='Complete shipping address (required)')),
                ('notes', models.TextField(blank=True, help_text='Optional order notes or special instructions', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total order amount (calculated from items)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the order was created')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product (required)', max_length=200)),
                ('quantity', models.IntegerField(help_text='Quantity ordered (minimum 1, required)', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (minimum 0.01, required)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this specific item', null=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.order')),
            ],
        ),
    ]
