# Generated by Django 4.2.23 on 2025-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology"),
                    ("programming", "Programming"),
                    ("web-development", "Web Development"),
                    ("mobile-development", "Mobile Development"),
                    ("data-science", "Data Science"),
                    ("artificial-intelligence", "Artificial Intelligence"),
                    ("machine-learning", "Machine Learning"),
                    ("cybersecurity", "Cybersecurity"),
                    ("cloud-computing", "Cloud Computing"),
                    ("devops", "DevOps"),
                    ("tutorial", "Tutorial"),
                    ("news", "News"),
                    ("opinion", "Opinion"),
                    ("review", "Review"),
                    ("case-study", "Case Study"),
                    ("best-practices", "Best Practices"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
